Breiz dev
ratt-ru/Stimela pull request #763
Opened 2022-08-24 12:24 UTC by Athanaseus

New `breizorro` release

2022-08-31 06:48 UTC, Athanaseus commented
restest this please

2022-08-31 06:48 UTC, Athanaseus commented
retest this please

2022-09-21 08:42 UTC, bennahugo requested changes
Minor:
Lets rather clean up that tmp folder which is currently only reaped by the server storage bot periodically when the disk space starts running low

2022-09-21 08:42 UTC, bennahugo commented on Jenkinsfile.sh
> +TMPDIR="$WORKSPACE_ROOT/tmp"
it may be worth writing a bash exit handler to handle cleanup:
```bash
function finish {
    rm -rf $TMPDIR
}
trap finish EXIT
```

2022-09-21 20:24 UTC, bennahugo approved these changes

2022-09-21 20:25 UTC, merged